version: '3'
services:
  database:
    image: postgres:12-bullseye
    container_name: postgres-container
    env_file:
      - .env
    ports:
      - '15432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dump:/docker-entrypoint-initdb.d/
    networks:
      - api_network

volumes:
  postgres_data:

networks:
  api_network:
    driver: bridge
